# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seedgeninj.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10seedgeninj.proto\x12\nseedgeninj\">\n\rLocateRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\x12\x15\n\rfunction_name\x18\x02 \x01(\t\"A\n\x0eLocateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04line\x18\x03 \x01(\r\"-\n\x0bViewRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\r\"/\n\x0cViewResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06source\x18\x02 \x01(\t\" \n\x0cShareRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"2\n\rShareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"8\n\nRunRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\x12\x12\n\nseeds_path\x18\x02 \x03(\t\"0\n\x0bRunResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x63overage\x18\x02 \x01(\t2\xfb\x01\n\x07SeedGen\x12?\n\x06Locate\x12\x19.seedgeninj.LocateRequest\x1a\x1a.seedgeninj.LocateResponse\x12\x39\n\x04View\x12\x17.seedgeninj.ViewRequest\x1a\x18.seedgeninj.ViewResponse\x12<\n\x05Share\x12\x18.seedgeninj.ShareRequest\x1a\x19.seedgeninj.ShareResponse\x12\x36\n\x03Run\x12\x16.seedgeninj.RunRequest\x1a\x17.seedgeninj.RunResponseB#Z!seedgen-injected/internal/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seedgeninj_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!seedgen-injected/internal/runtime'
  _globals['_LOCATEREQUEST']._serialized_start=32
  _globals['_LOCATEREQUEST']._serialized_end=94
  _globals['_LOCATERESPONSE']._serialized_start=96
  _globals['_LOCATERESPONSE']._serialized_end=161
  _globals['_VIEWREQUEST']._serialized_start=163
  _globals['_VIEWREQUEST']._serialized_end=208
  _globals['_VIEWRESPONSE']._serialized_start=210
  _globals['_VIEWRESPONSE']._serialized_end=257
  _globals['_SHAREREQUEST']._serialized_start=259
  _globals['_SHAREREQUEST']._serialized_end=291
  _globals['_SHARERESPONSE']._serialized_start=293
  _globals['_SHARERESPONSE']._serialized_end=343
  _globals['_RUNREQUEST']._serialized_start=345
  _globals['_RUNREQUEST']._serialized_end=401
  _globals['_RUNRESPONSE']._serialized_start=403
  _globals['_RUNRESPONSE']._serialized_end=451
  _globals['_SEEDGEN']._serialized_start=454
  _globals['_SEEDGEN']._serialized_end=705
# @@protoc_insertion_point(module_scope)
