# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import seedgeninj_pb2 as seedgeninj__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in seedgeninj_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SeedGenStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Locate = channel.unary_unary(
                '/seedgeninj.SeedGen/Locate',
                request_serializer=seedgeninj__pb2.LocateRequest.SerializeToString,
                response_deserializer=seedgeninj__pb2.LocateResponse.FromString,
                _registered_method=True)
        self.View = channel.unary_unary(
                '/seedgeninj.SeedGen/View',
                request_serializer=seedgeninj__pb2.ViewRequest.SerializeToString,
                response_deserializer=seedgeninj__pb2.ViewResponse.FromString,
                _registered_method=True)
        self.Share = channel.unary_unary(
                '/seedgeninj.SeedGen/Share',
                request_serializer=seedgeninj__pb2.ShareRequest.SerializeToString,
                response_deserializer=seedgeninj__pb2.ShareResponse.FromString,
                _registered_method=True)
        self.Run = channel.unary_unary(
                '/seedgeninj.SeedGen/Run',
                request_serializer=seedgeninj__pb2.RunRequest.SerializeToString,
                response_deserializer=seedgeninj__pb2.RunResponse.FromString,
                _registered_method=True)
        self.ExportCalls = channel.unary_unary(
                '/seedgeninj.SeedGen/ExportCalls',
                request_serializer=seedgeninj__pb2.ExportCallsRequest.SerializeToString,
                response_deserializer=seedgeninj__pb2.ExportCallsResponse.FromString,
                _registered_method=True)


class SeedGenServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Locate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def View(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Share(self, request, context):
        """share a file from the container to the shared directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportCalls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeedGenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Locate': grpc.unary_unary_rpc_method_handler(
                    servicer.Locate,
                    request_deserializer=seedgeninj__pb2.LocateRequest.FromString,
                    response_serializer=seedgeninj__pb2.LocateResponse.SerializeToString,
            ),
            'View': grpc.unary_unary_rpc_method_handler(
                    servicer.View,
                    request_deserializer=seedgeninj__pb2.ViewRequest.FromString,
                    response_serializer=seedgeninj__pb2.ViewResponse.SerializeToString,
            ),
            'Share': grpc.unary_unary_rpc_method_handler(
                    servicer.Share,
                    request_deserializer=seedgeninj__pb2.ShareRequest.FromString,
                    response_serializer=seedgeninj__pb2.ShareResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=seedgeninj__pb2.RunRequest.FromString,
                    response_serializer=seedgeninj__pb2.RunResponse.SerializeToString,
            ),
            'ExportCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportCalls,
                    request_deserializer=seedgeninj__pb2.ExportCallsRequest.FromString,
                    response_serializer=seedgeninj__pb2.ExportCallsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seedgeninj.SeedGen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seedgeninj.SeedGen', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeedGen(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Locate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedgeninj.SeedGen/Locate',
            seedgeninj__pb2.LocateRequest.SerializeToString,
            seedgeninj__pb2.LocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def View(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedgeninj.SeedGen/View',
            seedgeninj__pb2.ViewRequest.SerializeToString,
            seedgeninj__pb2.ViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Share(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedgeninj.SeedGen/Share',
            seedgeninj__pb2.ShareRequest.SerializeToString,
            seedgeninj__pb2.ShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedgeninj.SeedGen/Run',
            seedgeninj__pb2.RunRequest.SerializeToString,
            seedgeninj__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedgeninj.SeedGen/ExportCalls',
            seedgeninj__pb2.ExportCallsRequest.SerializeToString,
            seedgeninj__pb2.ExportCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
