# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seedgen.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rseedgen.proto\x12\x07seedgen\"0\n\x0eSeedGenRequest\x12\n\n\x02\x63p\x18\x01 \x01(\t\x12\x12\n\nharness_id\x18\x02 \x01(\t\"5\n\x0fSeedGenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tseed_path\x18\x02 \x01(\t2M\n\x07SeedGen\x12\x42\n\rGenerateSeeds\x12\x17.seedgen.SeedGenRequest\x1a\x18.seedgen.SeedGenResponseB\x1aZ\x18\x42igBoss/internal/seedgenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seedgen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030BigBoss/internal/seedgen'
  _globals['_SEEDGENREQUEST']._serialized_start=26
  _globals['_SEEDGENREQUEST']._serialized_end=74
  _globals['_SEEDGENRESPONSE']._serialized_start=76
  _globals['_SEEDGENRESPONSE']._serialized_end=129
  _globals['_SEEDGEN']._serialized_start=131
  _globals['_SEEDGEN']._serialized_end=208
# @@protoc_insertion_point(module_scope)
