# Format Alignment subgraph of SeedGen2

# Given call graph, align the format of the generated test cases with the required format specified in the harness

import logging
from typing import List
from seedgen2.agent.cot import CoT
from seedgen2.agent.graphs.predicates import get_related_functions
from seedgen2.agent.presets import SeedGen2GenerativeModel, SeedGen2InferModel
from seedgen2.agent.sowbot import Sowbot
from seedgen2.utils.functions import FunctionInfo
from seedgen2.utils.grpc import SeedD
from seedgen2.utils.seeds import SeedFeedback

PROMPT_ALIGN_ANALYSIS_FORMAT = """
Given the source code of a fuzzing harness, analyze the harness and tell me the required format of the test cases.

Here is the source code of the all related functions in the harness:
{related_functions}

As a result, you should write detailed format analysis of the harness, consisting of a comprehensive and easily digestable plaintext description, including but not limited to:

- Special data fields: location, type, encoding method, etc.
- Required well-known file type fields: location, file type, encoding method, special requirements, etc.
- Other special requirements.

After reading your analysis, anyone should be able to write an input generator for this harness.
"""

PROMPT_ALIGN_FORMAT = """
I am working on a fuzzing project and have developed a basic Python script to generate test cases for a fuzzing harness. However, I noticed that the current script does not generate test cases that are in the required format specified in the harness. Therefore, I need your help to improve the script to generate more comprehensive test cases. It is important to keep in mind that a harness usually requires a customized or modified format of test cases, so you need to carefully analyze the harness to understand the required format.

Focus on the function `LLVMFuzzerTestOneInput` in the harness. It is the entrance function of the harness. **Special data fields may be needed in the test case for the entrance function to work properly.**

Here is the current python script:
{script}

To help you understand the harness, I will also give you the source code of some functions related to the harness.
{related_functions}

To help you understand the harness, I already asked the developer to write a detailed format documentation for the harness:
{format_analysis}

You need to improve the script, so the test cases generated by the script will follow the required format specified in the harness, as described in the documentation above.
"""


def align_format(
        seedd: SeedD,
        script: str,
        seed_feedback: SeedFeedback,
        functions: List[FunctionInfo],
        harness_binary: str
):
    entrance_function = next(
        (func for func in seed_feedback.partially_covered_functions if func.function_name ==
         "LLVMFuzzerTestOneInput"),
        None
    )

    if entrance_function is None:
        logging.info("Entrance function is not found or is fully covered.")
        return

    related_functions = get_related_functions(
        seedd, functions, entrance_function.function_name)

    # Use infer model to generate the format analysis
    infer_model = SeedGen2InferModel().model
    prompt = PROMPT_ALIGN_ANALYSIS_FORMAT.format(
        related_functions=related_functions
    )
    format_analysis = infer_model.invoke(prompt).content # TODO: error handling

    model = SeedGen2GenerativeModel().model

    sowbot = Sowbot(seedd, harness_binary, model=model, include_example=False)

    prompt = PROMPT_ALIGN_FORMAT.format(
        script=script,
        related_functions=related_functions,
        format_analysis=format_analysis,
    )

    sowbot_result = sowbot.run(prompt)

    return sowbot_result, format_analysis
