# Format Alignment subgraph of SeedGen2

# Given call graph, align the format of the generated test cases with the required format specified in the harness

import logging
from typing import List
from seedgen2.agent.cot import CoT
from seedgen2.agent.graphs.predicates import get_related_functions
from seedgen2.agent.presets import SeedGen2GenerativeModel
from seedgen2.agent.sowbot import Sowbot
from seedgen2.utils.functions import FunctionInfo
from seedgen2.utils.grpc import SeedD
from seedgen2.utils.seeds import SeedFeedback

PROMPT_ALIGN_ANALYSIS_FORMAT = """
Given the source code of a fuzzing harness, analyze the harness and tell me the required format of the test cases.

Here is the source code of the all related functions in the harness:
{related_functions}

As a result, you should write detailed format analysis of the harness, including:

- Special data fields: location, type, encoding method, etc.
- Required well-known file type fields: location, file type, encoding method, special requirements, etc.
- Other special requirements.

After reading your analysis, anyone should be able to write a input generator for this harness.
"""

PROMPT_ALIGN_FORMAT = """
Help me modify the python script that generates test cases.
I noticed that the current script does not generate test cases that are in the required format specified in the harness. Noticed that a harness usually requires a customized or modified format of test cases, so you need to carefully analyze the harness to understand the required format.

Focus on the function `LLVMFuzzerTestOneInput` in the harness. It is the entrance function of the harness. **Special data fields may be needed in the test case for the entrance function to work properly.**

Here is the current python script:
{script}

To help you understand the harness, I will also give you the source code of some functions related to the harness.
{related_functions}

And here is the document of the required format:
{format_analysis}

You need to modify the script, so the test cases generated by the script will be in the required format specified in the harness.
"""


def align_format(
        seedd: SeedD,
        script: str,
        seed_feedback: SeedFeedback,
        functions: List[FunctionInfo],
        harness_binary: str
):
    entrance_function = next(
        (func for func in seed_feedback.partially_covered_functions if func.function_name ==
         "LLVMFuzzerTestOneInput"),
        None
    )

    if entrance_function is None:
        logging.info("Entrance function is not found or is fully covered.")
        return

    related_functions = get_related_functions(
        seedd, functions, entrance_function.function_name)

    # model = CoT(
    #     model=SeedGen2GenerativeModel().model,
    #     json_model=SeedGen2GenerativeModel().json_model
    # )

    model = SeedGen2GenerativeModel().model

    sowbot = Sowbot(seedd, harness_binary, model=model)

    prompt = PROMPT_ALIGN_FORMAT.format(
        script=script,
        related_functions=related_functions
    )

    sowbot_result = sowbot.run(prompt)
