# Predicates subgraph of SeedGen2

# Given coverage information (SeedFeedback), evaluate the predicates
from seedgen2.agent.cot import CoT
from seedgen2.agent.presets import SeedGen2InferModel
from seedgen2.agent.sowbot import Sowbot
from seedgen2.utils.callgraph import get_current_callgraph, get_ancestors, get_successors
from seedgen2.utils.functions import FunctionInfo, locate_function
from seedgen2.utils.grpc import SeedD
from seedgen2.utils.seeds import SeedFeedback

from typing import List
import logging
import random

PROMPT_flip_predicate = """
Help me modify the python script that generates test cases.
I noticed that the current script does not generate test cases that cover a certain predicate.

In the file `{file_path}`, the predicate is in function `{function_name}`.
The predicate is: `{predicate}`, which value is always `{predicate_value}` in all the generated test cases from the current script.

I want to flip the predicate value so we can cover more branches.

Here is the current python script:
{script}

To help you find a way to flip the predicate value, I will also give you the source code of some functions related.

{related_functions}

You need to modify the script, so the test cases generated by the script will help flip the predicate value.
"""


def get_related_functions(seedd: SeedD, functions: List[FunctionInfo], target_function: str) -> str:
    G = get_current_callgraph(seedd)
    # in the call graph G, we need to find all the predecessors of the target function

    predecessors = get_ancestors(G, target_function)
    directed_children = get_successors(G, target_function)

    related_function_list = predecessors + \
        [target_function] + directed_children

    related_functions_loc = [locate_function(
        f, functions) for f in related_function_list]

    related_functions_source = [
        (f.name, seedd.get_region_source(
            f.file_path, f.start_line, f.start_column, f.end_line, f.end_column)) for f in related_functions_loc if f is not None
    ]

    return "\n".join([f"Function `{name}`:\n{source}" for name, source in related_functions_source])


def improve_entrance_by_predicate(seedd: SeedD, script: str, seed_feedback: SeedFeedback, functions: List[FunctionInfo], harness_binary: str):

    # first, find the entrance function (LLVMFuzzerTestOneInput)
    for func in seed_feedback.partially_covered_functions:
        if func.function_name == "LLVMFuzzerTestOneInput":
            entrance_function = func
            break

    if entrance_function is None:
        logging.info("Entrance function is not found or is fully covered.")
        return

    # remember all the partially covered predicates
    old_predicates = entrance_function.partially_covered_predicates

    # from the partially covered predicates, we randomly pick one
    pred = random.choice(old_predicates)

    related_functions = get_related_functions(
        seedd, functions, entrance_function.function_name)

    pred_code = seedd.get_region_source(
        entrance_function.file_path,
        pred.start_line,
        pred.start_column,
        pred.end_line,
        pred.end_column,
    )

    predicate_value = "False" if pred.true_count == 0 and pred.false_count != 0 else (
        "True" if pred.true_count != 0 and pred.false_count == 0 else None)

    related_functions = get_related_functions(
        seedd, functions, entrance_function.function_name)

    prompt = PROMPT_flip_predicate.format(
        file_path=entrance_function.file_path,
        function_name=entrance_function.function_name,
        predicate=pred_code,
        predicate_value=predicate_value,
        script=script,
        related_functions=related_functions
    )

    # use a powerful inference model to flip the predicate value
    # sowbot = Sowbot(seedd, harness_binary, model=SeedGen2InferModel().model)
    sowbot = Sowbot(seedd, harness_binary, model=CoT())
    sowbot_result = sowbot.run(prompt)

    # let's check if the predicate value is flipped
    for func in sowbot_result.seed_evaluation_result.partially_covered_functions:
        if func.function_name == entrance_function.function_name:
            new_predicates = func.partially_covered_predicates
            break

    # check if the predicate value is flipped
    if new_predicates != old_predicates:
        print("Well, something changed. That's a good sign.")
        print(f"Old predicates: {old_predicates}")
        print(f"New predicates: {new_predicates}")
    else:
        print("Hmm, the predicate value is not flipped. Let's try again.")
        return None
