// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: seedd.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunSeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HarnessBinary string                 `protobuf:"bytes,1,opt,name=harness_binary,json=harnessBinary,proto3" json:"harness_binary,omitempty"`
	SeedsPath     []string               `protobuf:"bytes,2,rep,name=seeds_path,json=seedsPath,proto3" json:"seeds_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSeedsRequest) Reset() {
	*x = RunSeedsRequest{}
	mi := &file_seedd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSeedsRequest) ProtoMessage() {}

func (x *RunSeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSeedsRequest.ProtoReflect.Descriptor instead.
func (*RunSeedsRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{0}
}

func (x *RunSeedsRequest) GetHarnessBinary() string {
	if x != nil {
		return x.HarnessBinary
	}
	return ""
}

func (x *RunSeedsRequest) GetSeedsPath() []string {
	if x != nil {
		return x.SeedsPath
	}
	return nil
}

type GetMergedCoverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HarnessBinary string                 `protobuf:"bytes,1,opt,name=harness_binary,json=harnessBinary,proto3" json:"harness_binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMergedCoverageRequest) Reset() {
	*x = GetMergedCoverageRequest{}
	mi := &file_seedd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergedCoverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergedCoverageRequest) ProtoMessage() {}

func (x *GetMergedCoverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergedCoverageRequest.ProtoReflect.Descriptor instead.
func (*GetMergedCoverageRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{1}
}

func (x *GetMergedCoverageRequest) GetHarnessBinary() string {
	if x != nil {
		return x.HarnessBinary
	}
	return ""
}

type RunSeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coverage      string                 `protobuf:"bytes,1,opt,name=coverage,proto3" json:"coverage,omitempty"` // coverage will be return in JSON format
	Report        string                 `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`     // report will be return in plain text format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSeedsResponse) Reset() {
	*x = RunSeedsResponse{}
	mi := &file_seedd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSeedsResponse) ProtoMessage() {}

func (x *RunSeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSeedsResponse.ProtoReflect.Descriptor instead.
func (*RunSeedsResponse) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{2}
}

func (x *RunSeedsResponse) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *RunSeedsResponse) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

type GetRegionSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filepath      string                 `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"` // should be absolute path
	StartLine     uint64                 `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartColumn   uint64                 `protobuf:"varint,3,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndLine       uint64                 `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     uint64                 `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"` // exclusive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionSourceRequest) Reset() {
	*x = GetRegionSourceRequest{}
	mi := &file_seedd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionSourceRequest) ProtoMessage() {}

func (x *GetRegionSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionSourceRequest.ProtoReflect.Descriptor instead.
func (*GetRegionSourceRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{3}
}

func (x *GetRegionSourceRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *GetRegionSourceRequest) GetStartLine() uint64 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *GetRegionSourceRequest) GetStartColumn() uint64 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *GetRegionSourceRequest) GetEndLine() uint64 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *GetRegionSourceRequest) GetEndColumn() uint64 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

type GetRegionSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // source code in string format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionSourceResponse) Reset() {
	*x = GetRegionSourceResponse{}
	mi := &file_seedd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionSourceResponse) ProtoMessage() {}

func (x *GetRegionSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionSourceResponse.ProtoReflect.Descriptor instead.
func (*GetRegionSourceResponse) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{4}
}

func (x *GetRegionSourceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExtractFunctionSourceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Filepath string                 `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"` // should be absolute path
	// Types that are valid to be assigned to Location:
	//
	//	*ExtractFunctionSourceRequest_Line
	//	*ExtractFunctionSourceRequest_FunctionName
	Location      isExtractFunctionSourceRequest_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractFunctionSourceRequest) Reset() {
	*x = ExtractFunctionSourceRequest{}
	mi := &file_seedd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractFunctionSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractFunctionSourceRequest) ProtoMessage() {}

func (x *ExtractFunctionSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractFunctionSourceRequest.ProtoReflect.Descriptor instead.
func (*ExtractFunctionSourceRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractFunctionSourceRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *ExtractFunctionSourceRequest) GetLocation() isExtractFunctionSourceRequest_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ExtractFunctionSourceRequest) GetLine() uint64 {
	if x != nil {
		if x, ok := x.Location.(*ExtractFunctionSourceRequest_Line); ok {
			return x.Line
		}
	}
	return 0
}

func (x *ExtractFunctionSourceRequest) GetFunctionName() string {
	if x != nil {
		if x, ok := x.Location.(*ExtractFunctionSourceRequest_FunctionName); ok {
			return x.FunctionName
		}
	}
	return ""
}

type isExtractFunctionSourceRequest_Location interface {
	isExtractFunctionSourceRequest_Location()
}

type ExtractFunctionSourceRequest_Line struct {
	Line uint64 `protobuf:"varint,2,opt,name=line,proto3,oneof"` // fuzzy search, can be any line number in the function
}

type ExtractFunctionSourceRequest_FunctionName struct {
	FunctionName string `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3,oneof"` // function name to search for
}

func (*ExtractFunctionSourceRequest_Line) isExtractFunctionSourceRequest_Location() {}

func (*ExtractFunctionSourceRequest_FunctionName) isExtractFunctionSourceRequest_Location() {}

type ExtractFunctionSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // source code in string format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractFunctionSourceResponse) Reset() {
	*x = ExtractFunctionSourceResponse{}
	mi := &file_seedd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractFunctionSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractFunctionSourceResponse) ProtoMessage() {}

func (x *ExtractFunctionSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractFunctionSourceResponse.ProtoReflect.Descriptor instead.
func (*ExtractFunctionSourceResponse) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractFunctionSourceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetCallGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HarnessBinary string                 `protobuf:"bytes,1,opt,name=harness_binary,json=harnessBinary,proto3" json:"harness_binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallGraphRequest) Reset() {
	*x = GetCallGraphRequest{}
	mi := &file_seedd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallGraphRequest) ProtoMessage() {}

func (x *GetCallGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallGraphRequest.ProtoReflect.Descriptor instead.
func (*GetCallGraphRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{7}
}

func (x *GetCallGraphRequest) GetHarnessBinary() string {
	if x != nil {
		return x.HarnessBinary
	}
	return ""
}

type GetCallGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallGraph     string                 `protobuf:"bytes,1,opt,name=call_graph,json=callGraph,proto3" json:"call_graph,omitempty"` // call graph in JSON format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallGraphResponse) Reset() {
	*x = GetCallGraphResponse{}
	mi := &file_seedd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallGraphResponse) ProtoMessage() {}

func (x *GetCallGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallGraphResponse.ProtoReflect.Descriptor instead.
func (*GetCallGraphResponse) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{8}
}

func (x *GetCallGraphResponse) GetCallGraph() string {
	if x != nil {
		return x.CallGraph
	}
	return ""
}

type GetFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HarnessBinary string                 `protobuf:"bytes,1,opt,name=harness_binary,json=harnessBinary,proto3" json:"harness_binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionsRequest) Reset() {
	*x = GetFunctionsRequest{}
	mi := &file_seedd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionsRequest) ProtoMessage() {}

func (x *GetFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionsRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{9}
}

func (x *GetFunctionsRequest) GetHarnessBinary() string {
	if x != nil {
		return x.HarnessBinary
	}
	return ""
}

type GetFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     string                 `protobuf:"bytes,1,opt,name=functions,proto3" json:"functions,omitempty"` // functions in JSON format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionsResponse) Reset() {
	*x = GetFunctionsResponse{}
	mi := &file_seedd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionsResponse) ProtoMessage() {}

func (x *GetFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seedd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionsResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_seedd_proto_rawDescGZIP(), []int{10}
}

func (x *GetFunctionsResponse) GetFunctions() string {
	if x != nil {
		return x.Functions
	}
	return ""
}

var File_seedd_proto protoreflect.FileDescriptor

var file_seedd_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x65, 0x65, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x53,
	0x65, 0x65, 0x64, 0x44, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x65, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x61, 0x72, 0x6e, 0x65,
	0x73, 0x73, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x65, 0x64, 0x73, 0x50, 0x61, 0x74, 0x68, 0x22, 0x41, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x61, 0x72,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x22, 0x46, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x31, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x83,
	0x01, 0x0a, 0x1c, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x25, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x1d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3c, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x68, 0x61,
	0x72, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x35, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x22, 0x3c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x61, 0x72,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x22, 0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xdb, 0x03, 0x0a, 0x05, 0x53, 0x65, 0x65, 0x64, 0x44,
	0x12, 0x3b, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x65, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x53,
	0x65, 0x65, 0x64, 0x44, 0x2e, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x52, 0x75, 0x6e,
	0x53, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x1f, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x52, 0x75, 0x6e, 0x53,
	0x65, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x1d, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62,
	0x0a, 0x15, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x23, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x53,
	0x65, 0x65, 0x64, 0x44, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x12, 0x1a, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6c, 0x6c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x2e, 0x53, 0x65,
	0x65, 0x64, 0x44, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x44, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x73, 0x65, 0x65, 0x64, 0x64, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seedd_proto_rawDescOnce sync.Once
	file_seedd_proto_rawDescData = file_seedd_proto_rawDesc
)

func file_seedd_proto_rawDescGZIP() []byte {
	file_seedd_proto_rawDescOnce.Do(func() {
		file_seedd_proto_rawDescData = protoimpl.X.CompressGZIP(file_seedd_proto_rawDescData)
	})
	return file_seedd_proto_rawDescData
}

var file_seedd_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_seedd_proto_goTypes = []any{
	(*RunSeedsRequest)(nil),               // 0: SeedD.RunSeedsRequest
	(*GetMergedCoverageRequest)(nil),      // 1: SeedD.GetMergedCoverageRequest
	(*RunSeedsResponse)(nil),              // 2: SeedD.RunSeedsResponse
	(*GetRegionSourceRequest)(nil),        // 3: SeedD.GetRegionSourceRequest
	(*GetRegionSourceResponse)(nil),       // 4: SeedD.GetRegionSourceResponse
	(*ExtractFunctionSourceRequest)(nil),  // 5: SeedD.ExtractFunctionSourceRequest
	(*ExtractFunctionSourceResponse)(nil), // 6: SeedD.ExtractFunctionSourceResponse
	(*GetCallGraphRequest)(nil),           // 7: SeedD.GetCallGraphRequest
	(*GetCallGraphResponse)(nil),          // 8: SeedD.GetCallGraphResponse
	(*GetFunctionsRequest)(nil),           // 9: SeedD.GetFunctionsRequest
	(*GetFunctionsResponse)(nil),          // 10: SeedD.GetFunctionsResponse
}
var file_seedd_proto_depIdxs = []int32{
	0,  // 0: SeedD.SeedD.RunSeeds:input_type -> SeedD.RunSeedsRequest
	1,  // 1: SeedD.SeedD.GetMergedCoverage:input_type -> SeedD.GetMergedCoverageRequest
	3,  // 2: SeedD.SeedD.GetRegionSource:input_type -> SeedD.GetRegionSourceRequest
	5,  // 3: SeedD.SeedD.ExtractFunctionSource:input_type -> SeedD.ExtractFunctionSourceRequest
	7,  // 4: SeedD.SeedD.GetCallGraph:input_type -> SeedD.GetCallGraphRequest
	9,  // 5: SeedD.SeedD.GetFunctions:input_type -> SeedD.GetFunctionsRequest
	2,  // 6: SeedD.SeedD.RunSeeds:output_type -> SeedD.RunSeedsResponse
	2,  // 7: SeedD.SeedD.GetMergedCoverage:output_type -> SeedD.RunSeedsResponse
	4,  // 8: SeedD.SeedD.GetRegionSource:output_type -> SeedD.GetRegionSourceResponse
	6,  // 9: SeedD.SeedD.ExtractFunctionSource:output_type -> SeedD.ExtractFunctionSourceResponse
	8,  // 10: SeedD.SeedD.GetCallGraph:output_type -> SeedD.GetCallGraphResponse
	10, // 11: SeedD.SeedD.GetFunctions:output_type -> SeedD.GetFunctionsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_seedd_proto_init() }
func file_seedd_proto_init() {
	if File_seedd_proto != nil {
		return
	}
	file_seedd_proto_msgTypes[5].OneofWrappers = []any{
		(*ExtractFunctionSourceRequest_Line)(nil),
		(*ExtractFunctionSourceRequest_FunctionName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seedd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seedd_proto_goTypes,
		DependencyIndexes: file_seedd_proto_depIdxs,
		MessageInfos:      file_seedd_proto_msgTypes,
	}.Build()
	File_seedd_proto = out.File
	file_seedd_proto_rawDesc = nil
	file_seedd_proto_goTypes = nil
	file_seedd_proto_depIdxs = nil
}
