# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seedgeninj.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10seedgeninj.proto\x12\nseedgeninj\"3\n\x0e\x43ompileRequest\x12!\n\x19\x65xpected_harness_binaries\x18\x01 \x03(\t\"<\n\x0f\x43ompileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10harness_binaries\x18\x02 \x03(\t\">\n\rLocateRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\x12\x15\n\rfunction_name\x18\x02 \x01(\t\"A\n\x0eLocateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04line\x18\x03 \x01(\r\"-\n\x0bViewRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\r\"/\n\x0cViewResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06source\x18\x02 \x01(\t\"8\n\nRunRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\x12\x12\n\nseeds_path\x18\x02 \x03(\t\"0\n\x0bRunResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x63overage\x18\x02 \x01(\t\"!\n\x0e\x45xecuteRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"G\n\x0f\x45xecuteResponse\x12\x14\n\x0creturn_value\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t2\xc5\x02\n\x07SeedGen\x12\x42\n\x07\x43ompile\x12\x1a.seedgeninj.CompileRequest\x1a\x1b.seedgeninj.CompileResponse\x12?\n\x06Locate\x12\x19.seedgeninj.LocateRequest\x1a\x1a.seedgeninj.LocateResponse\x12\x39\n\x04View\x12\x17.seedgeninj.ViewRequest\x1a\x18.seedgeninj.ViewResponse\x12\x36\n\x03Run\x12\x16.seedgeninj.RunRequest\x1a\x17.seedgeninj.RunResponse\x12\x42\n\x07\x45xecute\x12\x1a.seedgeninj.ExecuteRequest\x1a\x1b.seedgeninj.ExecuteResponseB+Z)SeedGen/seedgen-injected/internal/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seedgeninj_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)SeedGen/seedgen-injected/internal/runtime'
  _globals['_COMPILEREQUEST']._serialized_start=32
  _globals['_COMPILEREQUEST']._serialized_end=83
  _globals['_COMPILERESPONSE']._serialized_start=85
  _globals['_COMPILERESPONSE']._serialized_end=145
  _globals['_LOCATEREQUEST']._serialized_start=147
  _globals['_LOCATEREQUEST']._serialized_end=209
  _globals['_LOCATERESPONSE']._serialized_start=211
  _globals['_LOCATERESPONSE']._serialized_end=276
  _globals['_VIEWREQUEST']._serialized_start=278
  _globals['_VIEWREQUEST']._serialized_end=323
  _globals['_VIEWRESPONSE']._serialized_start=325
  _globals['_VIEWRESPONSE']._serialized_end=372
  _globals['_RUNREQUEST']._serialized_start=374
  _globals['_RUNREQUEST']._serialized_end=430
  _globals['_RUNRESPONSE']._serialized_start=432
  _globals['_RUNRESPONSE']._serialized_end=480
  _globals['_EXECUTEREQUEST']._serialized_start=482
  _globals['_EXECUTEREQUEST']._serialized_end=515
  _globals['_EXECUTERESPONSE']._serialized_start=517
  _globals['_EXECUTERESPONSE']._serialized_end=588
  _globals['_SEEDGEN']._serialized_start=591
  _globals['_SEEDGEN']._serialized_end=916
# @@protoc_insertion_point(module_scope)
