"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RunSeedsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARNESS_BINARY_FIELD_NUMBER: builtins.int
    SEEDS_PATH_FIELD_NUMBER: builtins.int
    harness_binary: builtins.str
    @property
    def seeds_path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        harness_binary: builtins.str = ...,
        seeds_path: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["harness_binary", b"harness_binary", "seeds_path", b"seeds_path"]) -> None: ...

global___RunSeedsRequest = RunSeedsRequest

@typing.final
class GetMergedCoverageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARNESS_BINARY_FIELD_NUMBER: builtins.int
    harness_binary: builtins.str
    def __init__(
        self,
        *,
        harness_binary: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["harness_binary", b"harness_binary"]) -> None: ...

global___GetMergedCoverageRequest = GetMergedCoverageRequest

@typing.final
class RunSeedsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COVERAGE_FIELD_NUMBER: builtins.int
    REPORT_FIELD_NUMBER: builtins.int
    coverage: builtins.str
    """coverage will be return in JSON format"""
    report: builtins.str
    """report will be return in plain text format"""
    def __init__(
        self,
        *,
        coverage: builtins.str = ...,
        report: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coverage", b"coverage", "report", b"report"]) -> None: ...

global___RunSeedsResponse = RunSeedsResponse

@typing.final
class GetRegionSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILEPATH_FIELD_NUMBER: builtins.int
    START_LINE_FIELD_NUMBER: builtins.int
    START_COLUMN_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    END_COLUMN_FIELD_NUMBER: builtins.int
    filepath: builtins.str
    """should be absolute path"""
    start_line: builtins.int
    start_column: builtins.int
    end_line: builtins.int
    end_column: builtins.int
    """exclusive"""
    def __init__(
        self,
        *,
        filepath: builtins.str = ...,
        start_line: builtins.int = ...,
        start_column: builtins.int = ...,
        end_line: builtins.int = ...,
        end_column: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["end_column", b"end_column", "end_line", b"end_line", "filepath", b"filepath", "start_column", b"start_column", "start_line", b"start_line"]) -> None: ...

global___GetRegionSourceRequest = GetRegionSourceRequest

@typing.final
class GetRegionSourceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    source: builtins.str
    """source code in string format"""
    def __init__(
        self,
        *,
        source: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["source", b"source"]) -> None: ...

global___GetRegionSourceResponse = GetRegionSourceResponse

@typing.final
class ExtractFunctionSourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILEPATH_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    FUNCTION_NAME_FIELD_NUMBER: builtins.int
    filepath: builtins.str
    """should be absolute path"""
    line: builtins.int
    """fuzzy search, can be any line number in the function"""
    function_name: builtins.str
    """function name to search for"""
    def __init__(
        self,
        *,
        filepath: builtins.str = ...,
        line: builtins.int = ...,
        function_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["function_name", b"function_name", "line", b"line", "location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["filepath", b"filepath", "function_name", b"function_name", "line", b"line", "location", b"location"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["location", b"location"]) -> typing.Literal["line", "function_name"] | None: ...

global___ExtractFunctionSourceRequest = ExtractFunctionSourceRequest

@typing.final
class ExtractFunctionSourceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    source: builtins.str
    """source code in string format"""
    def __init__(
        self,
        *,
        source: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["source", b"source"]) -> None: ...

global___ExtractFunctionSourceResponse = ExtractFunctionSourceResponse

@typing.final
class GetCallGraphRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARNESS_BINARY_FIELD_NUMBER: builtins.int
    harness_binary: builtins.str
    def __init__(
        self,
        *,
        harness_binary: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["harness_binary", b"harness_binary"]) -> None: ...

global___GetCallGraphRequest = GetCallGraphRequest

@typing.final
class GetCallGraphResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_GRAPH_FIELD_NUMBER: builtins.int
    call_graph: builtins.str
    """call graph in JSON format"""
    def __init__(
        self,
        *,
        call_graph: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["call_graph", b"call_graph"]) -> None: ...

global___GetCallGraphResponse = GetCallGraphResponse

@typing.final
class GetFunctionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARNESS_BINARY_FIELD_NUMBER: builtins.int
    harness_binary: builtins.str
    def __init__(
        self,
        *,
        harness_binary: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["harness_binary", b"harness_binary"]) -> None: ...

global___GetFunctionsRequest = GetFunctionsRequest

@typing.final
class GetFunctionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUNCTIONS_FIELD_NUMBER: builtins.int
    functions: builtins.str
    """functions in JSON format"""
    def __init__(
        self,
        *,
        functions: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["functions", b"functions"]) -> None: ...

global___GetFunctionsResponse = GetFunctionsResponse
