# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seedd.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'seedd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bseedd.proto\x12\x05SeedD\"=\n\x0fRunSeedsRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\x12\x12\n\nseeds_path\x18\x02 \x03(\t\"2\n\x18GetMergedCoverageRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\"4\n\x10RunSeedsResponse\x12\x10\n\x08\x63overage\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t\"z\n\x16GetRegionSourceRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x12\n\nstart_line\x18\x02 \x01(\x04\x12\x14\n\x0cstart_column\x18\x03 \x01(\x04\x12\x10\n\x08\x65nd_line\x18\x04 \x01(\x04\x12\x12\n\nend_column\x18\x05 \x01(\x04\")\n\x17GetRegionSourceResponse\x12\x0e\n\x06source\x18\x01 \x01(\t\"e\n\x1c\x45xtractFunctionSourceRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0e\n\x04line\x18\x02 \x01(\x04H\x00\x12\x17\n\rfunction_name\x18\x03 \x01(\tH\x00\x42\n\n\x08location\"/\n\x1d\x45xtractFunctionSourceResponse\x12\x0e\n\x06source\x18\x01 \x01(\t\"-\n\x13GetCallGraphRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\"*\n\x14GetCallGraphResponse\x12\x12\n\ncall_graph\x18\x01 \x01(\t\"-\n\x13GetFunctionsRequest\x12\x16\n\x0eharness_binary\x18\x01 \x01(\t\")\n\x14GetFunctionsResponse\x12\x11\n\tfunctions\x18\x01 \x01(\t2\xdb\x03\n\x05SeedD\x12;\n\x08RunSeeds\x12\x16.SeedD.RunSeedsRequest\x1a\x17.SeedD.RunSeedsResponse\x12M\n\x11GetMergedCoverage\x12\x1f.SeedD.GetMergedCoverageRequest\x1a\x17.SeedD.RunSeedsResponse\x12P\n\x0fGetRegionSource\x12\x1d.SeedD.GetRegionSourceRequest\x1a\x1e.SeedD.GetRegionSourceResponse\x12\x62\n\x15\x45xtractFunctionSource\x12#.SeedD.ExtractFunctionSourceRequest\x1a$.SeedD.ExtractFunctionSourceResponse\x12G\n\x0cGetCallGraph\x12\x1a.SeedD.GetCallGraphRequest\x1a\x1b.SeedD.GetCallGraphResponse\x12G\n\x0cGetFunctions\x12\x1a.SeedD.GetFunctionsRequest\x1a\x1b.SeedD.GetFunctionsResponseB\x18Z\x16seedd/internal/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seedd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026seedd/internal/runtime'
  _globals['_RUNSEEDSREQUEST']._serialized_start=22
  _globals['_RUNSEEDSREQUEST']._serialized_end=83
  _globals['_GETMERGEDCOVERAGEREQUEST']._serialized_start=85
  _globals['_GETMERGEDCOVERAGEREQUEST']._serialized_end=135
  _globals['_RUNSEEDSRESPONSE']._serialized_start=137
  _globals['_RUNSEEDSRESPONSE']._serialized_end=189
  _globals['_GETREGIONSOURCEREQUEST']._serialized_start=191
  _globals['_GETREGIONSOURCEREQUEST']._serialized_end=313
  _globals['_GETREGIONSOURCERESPONSE']._serialized_start=315
  _globals['_GETREGIONSOURCERESPONSE']._serialized_end=356
  _globals['_EXTRACTFUNCTIONSOURCEREQUEST']._serialized_start=358
  _globals['_EXTRACTFUNCTIONSOURCEREQUEST']._serialized_end=459
  _globals['_EXTRACTFUNCTIONSOURCERESPONSE']._serialized_start=461
  _globals['_EXTRACTFUNCTIONSOURCERESPONSE']._serialized_end=508
  _globals['_GETCALLGRAPHREQUEST']._serialized_start=510
  _globals['_GETCALLGRAPHREQUEST']._serialized_end=555
  _globals['_GETCALLGRAPHRESPONSE']._serialized_start=557
  _globals['_GETCALLGRAPHRESPONSE']._serialized_end=599
  _globals['_GETFUNCTIONSREQUEST']._serialized_start=601
  _globals['_GETFUNCTIONSREQUEST']._serialized_end=646
  _globals['_GETFUNCTIONSRESPONSE']._serialized_start=648
  _globals['_GETFUNCTIONSRESPONSE']._serialized_end=689
  _globals['_SEEDD']._serialized_start=692
  _globals['_SEEDD']._serialized_end=1167
# @@protoc_insertion_point(module_scope)
