import logging
from typing import List
from seedgen2.graphs.plainbot import Plainbot
from seedgen2.presets import SeedGen2GenerativeModel
from seedgen2.graphs.sowbot import Sowbot, SowbotResult
from seedgen2.utils.grpc import SeedD
from seedgen2.utils.seeds import SeedFeedback
from seedgen2.utils.functions import FunctionInfo
from seedgen2.agents.predicates import get_related_functions

PROMPT_ALIGNMENT = """
I am working on a fuzzing project and have developed a Python script to generate test cases for a fuzzing harness. However, I noticed that the current script might be missing some details in the overall structure of a test case, as per the test case structure documentation. Therefore, I need your help to improve the script to generate more comprehensive and correct test cases.

Here is the current python script:
{script}

To help you understand the harness, this is the test case structure documentation that I refered to:
{structure_documentation}

You need to improve the script, so the test cases generated by the script will follow the required structure specified in the harness, as described in the documentation above.
"""

PROMPT_GENERATE_STRUCTURE_DOCUMENTATION = """
Given the source code of a fuzzing harness, please analyze it and write down the required structure of the test cases.

Here is the source code of the all related functions in the harness:
{related_functions}

As a result, you should write detailed structure documentation of the harness, consisting of a comprehensive and easily digestable plaintext description, including but not limited to:

- Headers or metadata fields and their characteristics.
- Specific data fields: location, type, encoding method, etc.
- Emphasize usage of common file types' contents within the test structure: their location, fields, specific requirements, etc.
- Other specific requirements.

Please ONLY give the detailed test case structure, and DO NOT include any concrete examples or guidance.
"""

PROMPT_IMPROVE_STRUCTURE_DOCUMENTATION = """
I am working on writing a documentation about the structure of a test case for a specific test harness. However, I've noticed that the current version of my documentation doesn't fully document everything that a test case requires. Therefore, I need your help to improve my test case structure documentation. Your tasks are:

- Analyze the source code of the harness and fully understand it.
- Find out the parts in the harness source that are not documented in the documentation, and add them to the documentation.
- Find out if there are any parts in the documentation that are incorrect, i.e. don't align with the source code, and correct them.

Here is the source code of the all related functions in the harness:
{related_functions}

Here is the current test case structure documentation:
{structure_documentation}

Please ONLY include the updated test case structure documentation in your response, and DO NOT include any concrete examples or guidance.
"""


def align_script(
        seedd: SeedD,
        script: str,
        structure_documentation: str,
        harness_binary: str
) -> SowbotResult:
    # Use generative model to improve the current script
    model = SeedGen2GenerativeModel().model
    prompt = PROMPT_ALIGNMENT.format(
        script=script,
        structure_documentation=structure_documentation,
    )

    sowbot = Sowbot(seedd, harness_binary, model=model, include_example=False)

    return sowbot.run(prompt)


def update_doc(
        seedd: SeedD,
        seed_feedback: SeedFeedback,
        functions: List[FunctionInfo],
        previous_doc: str = "",
) -> str:
    entrance_function = next(
        (func for func in seed_feedback.partially_covered_functions if func.function_name ==
         "LLVMFuzzerTestOneInput"),
        None
    )

    if entrance_function is None:
        logging.info("Entrance function is not found or is fully covered.")
        return

    related_functions = get_related_functions(
        seedd, functions, entrance_function.function_name)

    model = SeedGen2GenerativeModel().model

    if previous_doc == "":
        prompt = PROMPT_GENERATE_STRUCTURE_DOCUMENTATION.format(
            related_functions=related_functions
        )
    else:
        prompt = PROMPT_IMPROVE_STRUCTURE_DOCUMENTATION.format(
            related_functions=related_functions,
            structure_documentation=previous_doc
        )

    plainbot = Plainbot(model=model)
    return plainbot.run(prompt)
